[package]
name = "speedtest-fileserver-rs"
version = "0.2.0"
authors = ["mikevs <mikevs@xs4all.net>"]
edition = "2018"

[dependencies]
bytes = "0.5"
clap = "2.32.0"
http = "0.2"
human-size = "0.4.0"
hyper = "0.13"
rand = "0.7.3"
rand_core = "0.5"
tokio = { version = "0.2", features = ["full"] }
