[package]
name = "speedtest-fileserver-rs"
version = "0.1.0"
authors = ["mikevs <mikevs@xs4all.net>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
human-size = "0.4.0"
hyper = "0.12.24"
http = "0.1.15"
bytes = "0.4.11"
rand_xoshiro = "0.1.0"
rand = "0.6.5"
clap = "2.32.0"
