#! /bin/sh

### BEGIN INIT INFO
# Provides:             speedtest-fileserver
# Required-Start:       $network
# Required-Stop:        $network
# Default-Start:        2 3 4 5
# Default-Stop:         
# Short-Description:    Speedtest fileserver
### END INIT INFO

set -e

test -x /usr/sbin/speedtest-fileserver-rs || exit 0

. /lib/lsb/init-functions

# If systemd is installed, we never actually get here.
exit 1

